### ISSUE TITLE
No longer contributing?

### ISSUE THREAD

**Issue by synuns** [ukjinjang/react-channel-plugin#66]
As of December 15, There is some big changes to the ChannelTalk API schema.

https://developers.channel.io/docs/upcoming-changes-to-open-api-231215-~

The library does not currently support new versions.
So I'm seeing a lot of warnings right now, and we know you're aware of that.

<img width="383" alt="image" src="https://github.com/ukjinjang/react-channel-plugin/assets/57736547/7c34b213-cb01-4f53-bda6-a464eb7f7a14">

However, we're still seeing pretty high numbers, with 2k weekly downloads.

What do you think about doing more work to keep up with the new version for a lot of developers? 
I'd be happy to contribute. I'm here for you.

**Comment by ukjinjang** [comment]
First of all, thanks for the comment.

And yes, it has been a while since I've maintained the package, and many APIs have been added or removed. Therefore, I've updated the package and released a new version, [3.0.0-rc.0](https://github.com/ukjinjang/react-channel-plugin/releases/tag/v3.0.0-rc.0).

Please check out the newer version and let me know if there are any issues.
